# Generated by Django 3.0.7 on 2020-06-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='product_id',
            new_name='product',
        ),
    ]
