# Generated by Django 3.0.7 on 2020-06-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20200617_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
